In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a)



[1 2 3]


In [ ]:
"""Tells you number of rows and columns"""
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print (a.shape)


(2, 3)


In [ ]:
import numpy as np
list1 = np.array([1,2,3,4])
list2 = np.array([5,6,7,8])
list3=list1*list2
print(list3)


[ 5 12 21 32]


In [ ]:
'''change the size of array'''
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
"""Reshape is resizing the array"""
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print (b)


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
a = np.arange(24)
print (a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
import numpy as np
x = np.empty([3,2], float)
print (x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
"""Numpy slicing"""
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


In [ ]:
"""Reverse slicing"""
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])


[5 6]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])


[1 3 5 7]


In [ ]:
import numpy as np
a = np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
                [18,19,32]])
print(a[1:,1:])
print(a[:2,:2])
print(a[:2,1:])
print(a[2:,1:])


[[ 5  6]
 [ 8  9]
 [19 32]]
[[1 2]
 [4 5]]
[[2 3]
 [5 6]]
[[ 8  9]
 [19 32]]


In [ ]:
"""Iteration"""
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)


[1 2 3]
[4 5 6]


In [ ]:
import numpy as np
a = np.random.rand(8)
print(a)



[0.39160745 0.56284032 0.27680895 0.40390466 0.28682389 0.39171533
 0.68931229 0.52900343]
